// SPDX-License-Identifier: MIT
pragma solidity 0.8.23;

import {IPool} from "@aave/interfaces/IPool.sol";
import {IERC20Metadata} from "@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata.sol";
import {IWETH} from "@src/interfaces/IWETH.sol";

import {CreditPosition, DebtPosition} from "@src/libraries/LoanLibrary.sol";
import {CopyLimitOrder, LimitOrder} from "@src/libraries/OfferLibrary.sol";

import {IPriceFeed} from "@src/oracle/IPriceFeed.sol";

import {NonTransferrableScaledTokenV1_2} from "@deprecated/token/NonTransferrableScaledTokenV1_2.sol";
import {NonTransferrableToken} from "@src/token/NonTransferrableToken.sol";
import {NonTransferrableScaledTokenV1_5} from "@src/v1.5/token/NonTransferrableScaledTokenV1_5.sol";

struct User {
    // The user's loan offer
    LimitOrder loanOffer;
    // The user's borrow offer
    LimitOrder borrowOffer;
    // The user-defined opening limit CR. If not set, the protocol's crOpening is used.
    uint256 openingLimitBorrowCR;
    // Whether the user has disabled all credit positions for sale
    bool allCreditPositionsForSaleDisabled;
}

struct UserCopyLimitOrders {
    // the address to copy the limit orders from
    address copyAddress;
    // the loan offer copy parameters (null means no copy)
    CopyLimitOrder copyLoanOffer;
    // the borrow offer copy parameters (null means no copy)
    CopyLimitOrder copyBorrowOffer;
}

struct FeeConfig {
    // annual percentage rate of the protocol swap fee
    uint256 swapFeeAPR; // 0.005e18 = 0.5%
    // fee for fractionalizing credit positions
    uint256 fragmentationFee;// 5e6
    // percent of the futureValue to be given to the liquidator
    uint256 liquidationRewardPercent; // 0.05e18 = 5%
    // percent of collateral remainder to be split with protocol on profitable liquidations for overdue loans
    uint256 overdueCollateralProtocolPercent;// 0.01e18 = 1%
    // percent of collateral to be split with protocol on profitable liquidations
    uint256 collateralProtocolPercent;// 0.1e18 = 10%
    // address to receive protocol fees
    address feeRecipient;
}

struct RiskConfig {
    // minimum collateral ratio for opening a loan
    uint256 crOpening;// 1.5e18
    // maximum collateral ratio for liquidation
    uint256 crLiquidation; // 1.3e18
    // minimum credit value of loans
    uint256 minimumCreditBorrowAToken; // 5e6
    // maximum amount of deposited borrowed aTokens
    uint256 borrowATokenCap;// 1M USDC
    // minimum tenor for a loan
    uint256 minTenor;// 1 hour
    // maximum tenor for a loan
    uint256 maxTenor;// 5 years
}

struct Oracle {
    // price feed oracle
    IPriceFeed priceFeed;// priceFeed contract
    // variable pool borrow rate
    uint128 variablePoolBorrowRate;// default 0  update later by admin
    // timestamp of the last update
    uint64 variablePoolBorrowRateUpdatedAt; //timestamp
    // stale rate interval
    uint64 variablePoolBorrowRateStaleRateInterval;// 0 seconds
}

struct Data {
    // mapping of User structs
    mapping(address => User) users;
    // mapping of DebtPosition structs
    mapping(uint256 => DebtPosition) debtPositions;
    // mapping of CreditPosition structs
    mapping(uint256 => CreditPosition) creditPositions;
    // next debt position id
    uint256 nextDebtPositionId;//from 0
    // next credit position id
    uint256 nextCreditPositionId;// from uint128 position
    // Wrapped Ether contract address
    IWETH weth; // WETH9
    // the token used by borrowers to collateralize their loans
    IERC20Metadata underlyingCollateralToken; // WETH
    // the token lent from lenders to borrowers
    IERC20Metadata underlyingBorrowToken;// USDC
    // Size deposit underlying collateral token
    NonTransferrableToken collateralToken;// new NonTransferrableToken() szWETH   //@note NonTransferable only allow Size contract interaction
    // Size deposit underlying borrow aToken v1.2
    NonTransferrableScaledTokenV1_2 borrowATokenV1_2; // new NonTransferrableScaledTokenV1_2() szaUSDC . Scaled meant scale with aave index
    // Size tokenized debt
    NonTransferrableToken debtToken;// new NonTransferrableToken() szDebt_USDC
    // Variable Pool (Aave v3)
    IPool variablePool; // AAVE V3 pool contract
    // Multicall lock to check if multicall is in progress
    bool isMulticall;
    // Size deposit underlying borrow aToken v1.5
    NonTransferrableScaledTokenV1_5 borrowATokenV1_5;// unique token generated by factory. link between USDC/WETH saUSDC . pegged to USDC. equal value to aaveV3PoolToken.scaledBalanceOf
    // mapping of copy limit orders v1.6.1
    mapping(address => UserCopyLimitOrders) usersCopyLimitOrders;
}

struct State {
    // the fee configuration struct
    FeeConfig feeConfig;
    // the risk configuration struct
    RiskConfig riskConfig;
    // the oracle configuration struct
    Oracle oracle;
    // the protocol data (cannot be updated)
    Data data;
}

/// @title SizeStorage
/// @custom:security-contact security@size.credit
/// @author Size (https://size.credit/)
/// @notice Storage for the Size protocol
/// @dev WARNING: Changing the order of the variables or inner structs in this contract may break the storage layout
abstract contract SizeStorage {
    State internal state;
}
