/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StakingRewards } from "./StakingRewards";
export type { StakingRewardsFactory } from "./StakingRewardsFactory";
export type { StakingRewardsManager } from "./StakingRewardsManager";
