/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace StakingRewardsManager {
  export type StakingConfigStruct = {
    rewardsDuration: BigNumberish;
    rewardAmount: BigNumberish;
  };

  export type StakingConfigStructOutput = [
    rewardsDuration: bigint,
    rewardAmount: bigint
  ] & { rewardsDuration: bigint; rewardAmount: bigint };
}

export interface StakingRewardsManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "BUILDER_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "EXECUTOR_ROLE"
      | "MAINTAINER_ROLE"
      | "SUPPORT_ROLE"
      | "addStakingRewardsContract"
      | "createNewStakingRewardsContract"
      | "getRoleAdmin"
      | "getStakingContract"
      | "grantRole"
      | "hasRole"
      | "initialize"
      | "recoverERC20"
      | "recoverERC20FromStaking"
      | "removeStakingRewardsContract"
      | "renounceRole"
      | "revokeRole"
      | "rewardToken"
      | "setStakingConfig"
      | "setStakingRewardsFactory"
      | "stakingConfigs"
      | "stakingContracts"
      | "stakingContractsLength"
      | "stakingExists"
      | "stakingRewardsFactory"
      | "supportsInterface"
      | "topUp"
      | "transferStakingOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Initialized"
      | "PeriodFinishUpdated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "StakingAdded"
      | "StakingConfigChanged"
      | "StakingRemoved"
      | "StakingRewardsFactoryChanged"
      | "ToppedUp"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BUILDER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EXECUTOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAINTAINER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SUPPORT_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addStakingRewardsContract",
    values: [AddressLike, StakingRewardsManager.StakingConfigStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "createNewStakingRewardsContract",
    values: [AddressLike, StakingRewardsManager.StakingConfigStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStakingContract",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recoverERC20",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recoverERC20FromStaking",
    values: [AddressLike, AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeStakingRewardsContract",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rewardToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setStakingConfig",
    values: [AddressLike, StakingRewardsManager.StakingConfigStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setStakingRewardsFactory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stakingConfigs",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stakingContracts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakingContractsLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stakingExists",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stakingRewardsFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "topUp",
    values: [AddressLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "transferStakingOwnership",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "BUILDER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EXECUTOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAINTAINER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SUPPORT_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addStakingRewardsContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createNewStakingRewardsContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStakingContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recoverERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recoverERC20FromStaking",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeStakingRewardsContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rewardToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStakingConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStakingRewardsFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakingConfigs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakingContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakingContractsLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakingExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakingRewardsFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "topUp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferStakingOwnership",
    data: BytesLike
  ): Result;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PeriodFinishUpdatedEvent {
  export type InputTuple = [
    staking: AddressLike,
    newPeriodFinish: BigNumberish
  ];
  export type OutputTuple = [staking: string, newPeriodFinish: bigint];
  export interface OutputObject {
    staking: string;
    newPeriodFinish: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakingAddedEvent {
  export type InputTuple = [
    staking: AddressLike,
    config: StakingRewardsManager.StakingConfigStruct
  ];
  export type OutputTuple = [
    staking: string,
    config: StakingRewardsManager.StakingConfigStructOutput
  ];
  export interface OutputObject {
    staking: string;
    config: StakingRewardsManager.StakingConfigStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakingConfigChangedEvent {
  export type InputTuple = [
    staking: AddressLike,
    config: StakingRewardsManager.StakingConfigStruct
  ];
  export type OutputTuple = [
    staking: string,
    config: StakingRewardsManager.StakingConfigStructOutput
  ];
  export interface OutputObject {
    staking: string;
    config: StakingRewardsManager.StakingConfigStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakingRemovedEvent {
  export type InputTuple = [staking: AddressLike];
  export type OutputTuple = [staking: string];
  export interface OutputObject {
    staking: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakingRewardsFactoryChangedEvent {
  export type InputTuple = [stakingFactory: AddressLike];
  export type OutputTuple = [stakingFactory: string];
  export interface OutputObject {
    stakingFactory: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ToppedUpEvent {
  export type InputTuple = [
    staking: AddressLike,
    config: StakingRewardsManager.StakingConfigStruct
  ];
  export type OutputTuple = [
    staking: string,
    config: StakingRewardsManager.StakingConfigStructOutput
  ];
  export interface OutputObject {
    staking: string;
    config: StakingRewardsManager.StakingConfigStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StakingRewardsManager extends BaseContract {
  connect(runner?: ContractRunner | null): StakingRewardsManager;
  waitForDeployment(): Promise<this>;

  interface: StakingRewardsManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  BUILDER_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  EXECUTOR_ROLE: TypedContractMethod<[], [string], "view">;

  MAINTAINER_ROLE: TypedContractMethod<[], [string], "view">;

  SUPPORT_ROLE: TypedContractMethod<[], [string], "view">;

  addStakingRewardsContract: TypedContractMethod<
    [staking: AddressLike, config: StakingRewardsManager.StakingConfigStruct],
    [void],
    "nonpayable"
  >;

  createNewStakingRewardsContract: TypedContractMethod<
    [
      stakingToken: AddressLike,
      config: StakingRewardsManager.StakingConfigStruct
    ],
    [void],
    "nonpayable"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getStakingContract: TypedContractMethod<[i: BigNumberish], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<
    [reward: AddressLike, factory: AddressLike],
    [void],
    "nonpayable"
  >;

  recoverERC20: TypedContractMethod<
    [tokenAddress: AddressLike, tokenAmount: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;

  recoverERC20FromStaking: TypedContractMethod<
    [
      staking: AddressLike,
      tokenAddress: AddressLike,
      tokenAmount: BigNumberish,
      to: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  removeStakingRewardsContract: TypedContractMethod<
    [i: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  rewardToken: TypedContractMethod<[], [string], "view">;

  setStakingConfig: TypedContractMethod<
    [staking: AddressLike, config: StakingRewardsManager.StakingConfigStruct],
    [void],
    "nonpayable"
  >;

  setStakingRewardsFactory: TypedContractMethod<
    [factory: AddressLike],
    [void],
    "nonpayable"
  >;

  stakingConfigs: TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { rewardsDuration: bigint; rewardAmount: bigint }],
    "view"
  >;

  stakingContracts: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  stakingContractsLength: TypedContractMethod<[], [bigint], "view">;

  stakingExists: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  stakingRewardsFactory: TypedContractMethod<[], [string], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  topUp: TypedContractMethod<
    [source: AddressLike, indices: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  transferStakingOwnership: TypedContractMethod<
    [staking: AddressLike, newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "BUILDER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "EXECUTOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAINTAINER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SUPPORT_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addStakingRewardsContract"
  ): TypedContractMethod<
    [staking: AddressLike, config: StakingRewardsManager.StakingConfigStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createNewStakingRewardsContract"
  ): TypedContractMethod<
    [
      stakingToken: AddressLike,
      config: StakingRewardsManager.StakingConfigStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getStakingContract"
  ): TypedContractMethod<[i: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [reward: AddressLike, factory: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recoverERC20"
  ): TypedContractMethod<
    [tokenAddress: AddressLike, tokenAmount: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recoverERC20FromStaking"
  ): TypedContractMethod<
    [
      staking: AddressLike,
      tokenAddress: AddressLike,
      tokenAmount: BigNumberish,
      to: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeStakingRewardsContract"
  ): TypedContractMethod<[i: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rewardToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setStakingConfig"
  ): TypedContractMethod<
    [staking: AddressLike, config: StakingRewardsManager.StakingConfigStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setStakingRewardsFactory"
  ): TypedContractMethod<[factory: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakingConfigs"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { rewardsDuration: bigint; rewardAmount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "stakingContracts"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "stakingContractsLength"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "stakingExists"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "stakingRewardsFactory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "topUp"
  ): TypedContractMethod<
    [source: AddressLike, indices: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferStakingOwnership"
  ): TypedContractMethod<
    [staking: AddressLike, newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "PeriodFinishUpdated"
  ): TypedContractEvent<
    PeriodFinishUpdatedEvent.InputTuple,
    PeriodFinishUpdatedEvent.OutputTuple,
    PeriodFinishUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "StakingAdded"
  ): TypedContractEvent<
    StakingAddedEvent.InputTuple,
    StakingAddedEvent.OutputTuple,
    StakingAddedEvent.OutputObject
  >;
  getEvent(
    key: "StakingConfigChanged"
  ): TypedContractEvent<
    StakingConfigChangedEvent.InputTuple,
    StakingConfigChangedEvent.OutputTuple,
    StakingConfigChangedEvent.OutputObject
  >;
  getEvent(
    key: "StakingRemoved"
  ): TypedContractEvent<
    StakingRemovedEvent.InputTuple,
    StakingRemovedEvent.OutputTuple,
    StakingRemovedEvent.OutputObject
  >;
  getEvent(
    key: "StakingRewardsFactoryChanged"
  ): TypedContractEvent<
    StakingRewardsFactoryChangedEvent.InputTuple,
    StakingRewardsFactoryChangedEvent.OutputTuple,
    StakingRewardsFactoryChangedEvent.OutputObject
  >;
  getEvent(
    key: "ToppedUp"
  ): TypedContractEvent<
    ToppedUpEvent.InputTuple,
    ToppedUpEvent.OutputTuple,
    ToppedUpEvent.OutputObject
  >;

  filters: {
    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "PeriodFinishUpdated(address,uint256)": TypedContractEvent<
      PeriodFinishUpdatedEvent.InputTuple,
      PeriodFinishUpdatedEvent.OutputTuple,
      PeriodFinishUpdatedEvent.OutputObject
    >;
    PeriodFinishUpdated: TypedContractEvent<
      PeriodFinishUpdatedEvent.InputTuple,
      PeriodFinishUpdatedEvent.OutputTuple,
      PeriodFinishUpdatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "StakingAdded(address,tuple)": TypedContractEvent<
      StakingAddedEvent.InputTuple,
      StakingAddedEvent.OutputTuple,
      StakingAddedEvent.OutputObject
    >;
    StakingAdded: TypedContractEvent<
      StakingAddedEvent.InputTuple,
      StakingAddedEvent.OutputTuple,
      StakingAddedEvent.OutputObject
    >;

    "StakingConfigChanged(address,tuple)": TypedContractEvent<
      StakingConfigChangedEvent.InputTuple,
      StakingConfigChangedEvent.OutputTuple,
      StakingConfigChangedEvent.OutputObject
    >;
    StakingConfigChanged: TypedContractEvent<
      StakingConfigChangedEvent.InputTuple,
      StakingConfigChangedEvent.OutputTuple,
      StakingConfigChangedEvent.OutputObject
    >;

    "StakingRemoved(address)": TypedContractEvent<
      StakingRemovedEvent.InputTuple,
      StakingRemovedEvent.OutputTuple,
      StakingRemovedEvent.OutputObject
    >;
    StakingRemoved: TypedContractEvent<
      StakingRemovedEvent.InputTuple,
      StakingRemovedEvent.OutputTuple,
      StakingRemovedEvent.OutputObject
    >;

    "StakingRewardsFactoryChanged(address)": TypedContractEvent<
      StakingRewardsFactoryChangedEvent.InputTuple,
      StakingRewardsFactoryChangedEvent.OutputTuple,
      StakingRewardsFactoryChangedEvent.OutputObject
    >;
    StakingRewardsFactoryChanged: TypedContractEvent<
      StakingRewardsFactoryChangedEvent.InputTuple,
      StakingRewardsFactoryChangedEvent.OutputTuple,
      StakingRewardsFactoryChangedEvent.OutputObject
    >;

    "ToppedUp(address,tuple)": TypedContractEvent<
      ToppedUpEvent.InputTuple,
      ToppedUpEvent.OutputTuple,
      ToppedUpEvent.OutputObject
    >;
    ToppedUp: TypedContractEvent<
      ToppedUpEvent.InputTuple,
      ToppedUpEvent.OutputTuple,
      ToppedUpEvent.OutputObject
    >;
  };
}
