/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface StakingRewardsFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createStakingRewards"
      | "getStakingRewardsContract"
      | "getStakingRewardsContractCount"
      | "owner"
      | "renounceOwnership"
      | "stakingRewardsContracts"
      | "stakingRewardsImplementation"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "NewStakingRewardsContract" | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createStakingRewards",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStakingRewardsContract",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStakingRewardsContractCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stakingRewardsContracts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakingRewardsImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createStakingRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStakingRewardsContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStakingRewardsContractCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakingRewardsContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakingRewardsImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace NewStakingRewardsContractEvent {
  export type InputTuple = [
    index: BigNumberish,
    rewardToken: AddressLike,
    stakingToken: AddressLike,
    implementation: AddressLike
  ];
  export type OutputTuple = [
    index: bigint,
    rewardToken: string,
    stakingToken: string,
    implementation: string
  ];
  export interface OutputObject {
    index: bigint;
    rewardToken: string;
    stakingToken: string;
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StakingRewardsFactory extends BaseContract {
  connect(runner?: ContractRunner | null): StakingRewardsFactory;
  waitForDeployment(): Promise<this>;

  interface: StakingRewardsFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createStakingRewards: TypedContractMethod<
    [
      rewardsDistribution: AddressLike,
      rewardsToken: AddressLike,
      stakingToken: AddressLike
    ],
    [string],
    "nonpayable"
  >;

  getStakingRewardsContract: TypedContractMethod<
    [index: BigNumberish],
    [string],
    "view"
  >;

  getStakingRewardsContractCount: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  stakingRewardsContracts: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  stakingRewardsImplementation: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createStakingRewards"
  ): TypedContractMethod<
    [
      rewardsDistribution: AddressLike,
      rewardsToken: AddressLike,
      stakingToken: AddressLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getStakingRewardsContract"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getStakingRewardsContractCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakingRewardsContracts"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "stakingRewardsImplementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "NewStakingRewardsContract"
  ): TypedContractEvent<
    NewStakingRewardsContractEvent.InputTuple,
    NewStakingRewardsContractEvent.OutputTuple,
    NewStakingRewardsContractEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "NewStakingRewardsContract(uint256,address,address,address)": TypedContractEvent<
      NewStakingRewardsContractEvent.InputTuple,
      NewStakingRewardsContractEvent.OutputTuple,
      NewStakingRewardsContractEvent.OutputObject
    >;
    NewStakingRewardsContract: TypedContractEvent<
      NewStakingRewardsContractEvent.InputTuple,
      NewStakingRewardsContractEvent.OutputTuple,
      NewStakingRewardsContractEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
