/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPRBProxy,
  IPRBProxyInterface,
} from "../../../../contracts/sablier/interfaces/IPRBProxy";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "target",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "execute",
    outputs: [
      {
        internalType: "bytes",
        name: "response",
        type: "bytes",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IPRBProxy__factory {
  static readonly abi = _abi;
  static createInterface(): IPRBProxyInterface {
    return new Interface(_abi) as IPRBProxyInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IPRBProxy {
    return new Contract(address, _abi, runner) as unknown as IPRBProxy;
  }
}
