/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISablierV2ProxyTarget,
  ISablierV2ProxyTargetInterface,
} from "../../../../contracts/sablier/interfaces/ISablierV2ProxyTarget";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract ISablierV2Lockup",
        name: "lockup",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "streamId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "withdrawMax",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISablierV2ProxyTarget__factory {
  static readonly abi = _abi;
  static createInterface(): ISablierV2ProxyTargetInterface {
    return new Interface(_abi) as ISablierV2ProxyTargetInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISablierV2ProxyTarget {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ISablierV2ProxyTarget;
  }
}
