/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TestNFT } from "./TestNFT";
export type { TestTelcoin } from "./TestTelcoin";
export type { TestToken } from "./TestToken";
