/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBalanceHolder,
  IBalanceHolderInterface,
} from "../../../../contracts/zodiac/interfaces/IBalanceHolder";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBalanceHolder__factory {
  static readonly abi = _abi;
  static createInterface(): IBalanceHolderInterface {
    return new Interface(_abi) as IBalanceHolderInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IBalanceHolder {
    return new Contract(address, _abi, runner) as unknown as IBalanceHolder;
  }
}
