/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IReality,
  IRealityInterface,
} from "../../../../contracts/zodiac/interfaces/IReality";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "question_id",
        type: "bytes32",
      },
    ],
    name: "getBestAnswer",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
      {
        internalType: "enum Enum.Operation",
        name: "operation",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
    ],
    name: "getTransactionHash",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "question_id",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "requester",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "max_previous",
        type: "uint256",
      },
    ],
    name: "notifyOfArbitrationRequest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "question_id",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "answer",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "answerer",
        type: "address",
      },
    ],
    name: "submitAnswerByArbitrator",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IReality__factory {
  static readonly abi = _abi;
  static createInterface(): IRealityInterface {
    return new Interface(_abi) as IRealityInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IReality {
    return new Contract(address, _abi, runner) as unknown as IReality;
  }
}
