/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPRBProxy } from "./IPRBProxy";
export type { ISablierV2ProxyTarget } from "./ISablierV2ProxyTarget";
