/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  TestStream,
  TestStreamInterface,
} from "../../../../contracts/sablier/test/TestStream";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IERC20",
        name: "token_",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "_token",
    outputs: [
      {
        internalType: "contract IERC20",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "execute",
    outputs: [
      {
        internalType: "bytes",
        name: "response",
        type: "bytes",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "lastBlock",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561000f575f80fd5b5060405161030e38038061030e83398101604081905261002e91610052565b5f80546001600160a01b0319166001600160a01b039290921691909117905561007f565b5f60208284031215610062575f80fd5b81516001600160a01b0381168114610078575f80fd5b9392505050565b6102828061008c5f395ff3fe608060405260043610610033575f3560e01c80631cff79cd14610037578063806b984f14610060578063ecd0c0c314610083575b5f80fd5b61004a610045366004610151565b6100b9565b60405161005791906101da565b60405180910390f35b34801561006b575f80fd5b5061007560015481565b604051908152602001610057565b34801561008e575f80fd5b505f546100a1906001600160a01b031681565b6040516001600160a01b039091168152602001610057565b6060426001541461013b575f5460405163a9059cbb60e01b8152336004820152606460248201526001600160a01b039091169063a9059cbb906044016020604051808303815f875af1158015610111573d5f803e3d5ffd5b505050506040513d601f19601f820116820180604052508101906101359190610226565b50426001555b505060408051602081019091525f815292915050565b5f805f60408486031215610163575f80fd5b83356001600160a01b0381168114610179575f80fd5b9250602084013567ffffffffffffffff80821115610195575f80fd5b818601915086601f8301126101a8575f80fd5b8135818111156101b6575f80fd5b8760208285010111156101c7575f80fd5b6020830194508093505050509250925092565b5f602080835283518060208501525f5b81811015610206578581018301518582016040015282016101ea565b505f604082860101526040601f19601f8301168501019250505092915050565b5f60208284031215610236575f80fd5b81518015158114610245575f80fd5b939250505056fea2646970667358221220ffe008e7d6d7a3e03d684cdd3d7ba56de7c641b7cf99ef1a3ffbe2061984b00e64736f6c63430008170033";

type TestStreamConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TestStreamConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TestStream__factory extends ContractFactory {
  constructor(...args: TestStreamConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    token_: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(token_, overrides || {});
  }
  override deploy(
    token_: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(token_, overrides || {}) as Promise<
      TestStream & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): TestStream__factory {
    return super.connect(runner) as TestStream__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TestStreamInterface {
    return new Interface(_abi) as TestStreamInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): TestStream {
    return new Contract(address, _abi, runner) as unknown as TestStream;
  }
}
