/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBalanceHolder } from "./IBalanceHolder";
export type { IGuard } from "./IGuard";
export type { IReality } from "./IReality";
export type { IRealityETH } from "./IRealityETH";
