/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IRealityInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getBestAnswer"
      | "getTransactionHash"
      | "notifyOfArbitrationRequest"
      | "submitAnswerByArbitrator"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getBestAnswer",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransactionHash",
    values: [AddressLike, BigNumberish, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "notifyOfArbitrationRequest",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitAnswerByArbitrator",
    values: [BytesLike, BytesLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getBestAnswer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransactionHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "notifyOfArbitrationRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitAnswerByArbitrator",
    data: BytesLike
  ): Result;
}

export interface IReality extends BaseContract {
  connect(runner?: ContractRunner | null): IReality;
  waitForDeployment(): Promise<this>;

  interface: IRealityInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getBestAnswer: TypedContractMethod<
    [question_id: BytesLike],
    [string],
    "view"
  >;

  getTransactionHash: TypedContractMethod<
    [
      to: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      operation: BigNumberish,
      nonce: BigNumberish
    ],
    [string],
    "view"
  >;

  notifyOfArbitrationRequest: TypedContractMethod<
    [
      question_id: BytesLike,
      requester: AddressLike,
      max_previous: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  submitAnswerByArbitrator: TypedContractMethod<
    [question_id: BytesLike, answer: BytesLike, answerer: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getBestAnswer"
  ): TypedContractMethod<[question_id: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTransactionHash"
  ): TypedContractMethod<
    [
      to: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      operation: BigNumberish,
      nonce: BigNumberish
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "notifyOfArbitrationRequest"
  ): TypedContractMethod<
    [
      question_id: BytesLike,
      requester: AddressLike,
      max_previous: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitAnswerByArbitrator"
  ): TypedContractMethod<
    [question_id: BytesLike, answer: BytesLike, answerer: AddressLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
